Algoritmo "desconto"

Var
    Valor, Desconto, resultado: real
    produto: caracter
    
Inicio
       escreva ("Digite um Produto")
       leia (produto)
       escreva ("Valor do Produto")
       leia(valor)
       
        desconto <- valor * 0.005
        escreval(desconto)

        escreval(valor - desconto)
        
        escreva (resultado)

    
    

      
Fimalgoritmo